---
- name: Install apache and php
  hosts: all
  become: yes
  tasks:
    - name: install apache
      apt:
        name: apache2
        update_cache: yes
        state: present
    - name: install php
      apt:
        name:
          - php
          - libapache2-mod-php
          - php-mysql
        state: present
    - name: create info.php
      copy:
        dest: /var/www/html/info.php
        content: <?php phpinfo(); ?>
      notify:
        - restart apache2 service
  handlers:
    - name: restart apache2 service
      service:
        name: apache2
        enabled: yes
        state: restarted
